[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npx pnpm@9 install --frozen-lockfile"
]

[phases.build]
cmds = ["npx pnpm@9 --filter @df/web build"]

[start]
cmd = "cd apps/web && npx pnpm@9 start"