[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npx pnpm@9 install --frozen-lockfile"
]

[phases.build]
cmds = ["npx pnpm@9 --filter @df/api db:generate && npx pnpm@9 --filter @df/api build"]

[start]
cmd = "cd apps/api && node dist/src/main"