[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @df/api db:generate", "pnpm turbo build --filter=@df/api..."]

[start]
cmd = "cd apps/api && node dist/src/main"
